### ISSUE TITLE
Disk boot failure, please enter system disk and press enter.

### ISSUE THREAD

**Issue by eazysu** [adgsenpai/LinuxWin2USB#2]
During making of win11 bootable usb everything went fine but when reboot it won't boots, heres are ss inside the usb.
![Screenshot from 2024-09-17 23-01-05](https://github.com/user-attachments/assets/7f0f8c01-3360-4157-ab9d-7b404dd8527f)

**Comment by adgsenpai** [comment]
Will investigate and get back to you soon. Thanks for bringing this to my attention!

**Comment by eazysu** [comment]
I made usb using other repo, now i'm on windows.
